// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.EntityDOMElements = (function() {
    function EntityDOMElements(entity) {
      this.entity = entity;
      this.update = __bind(this.update, this);
      new EntityContainer(this.entity);
      this.entityProperties = new EntityProperties(this.entity);
      new EntityFunctions(this.entity);
    }

    EntityDOMElements.prototype.update = function() {
      return this.entityProperties.update();
    };

    return EntityDOMElements;

  })();

}).call(this);
