// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.SpaceClickListener = (function() {
    function SpaceClickListener(universe) {
      this.universe = universe;
      this.addEntity = __bind(this.addEntity, this);
      this.attachListeners = __bind(this.attachListeners, this);
      this.attachListeners();
    }

    SpaceClickListener.prototype.attachListeners = function() {
      return $canvas().on('dblclick', this.addEntity);
    };

    SpaceClickListener.prototype.addEntity = function(e) {
      var color, entity, entityCount, mouse, name, position;
      e.preventDefault();
      entityCount = this.universe.entities.length;
      name = "entity-" + (entityCount + 1);
      mouse = getMouse(e);
      position = new Vector(mouse.x, mouse.y);
      color = randomColor();
      entity = new Entity({
        name: name,
        position: position,
        color: color
      });
      this.universe.addEntity(entity);
      jumpToPageBottom();
      return forceRedraw();
    };

    return SpaceClickListener;

  })();

}).call(this);
