// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.SpaceDimensionInputs = (function() {
    function SpaceDimensionInputs() {
      this.attachListeners = __bind(this.attachListeners, this);
      this.setInitialValues = __bind(this.setInitialValues, this);
      this.space = document.getElementById('space');
      this.$spaceWidth = $("#space-width");
      this.$spaceHeight = $("#space-height");
      this.setInitialValues();
      this.attachListeners();
    }

    SpaceDimensionInputs.prototype.setInitialValues = function() {
      this.$spaceWidth.val(this.space.width);
      return this.$spaceHeight.val(this.space.height);
    };

    SpaceDimensionInputs.prototype.attachListeners = function() {
      this.$spaceWidth.on('change', (function(_this) {
        return function() {
          return _this.space.width = _this.$spaceWidth.val();
        };
      })(this));
      return this.$spaceHeight.on('change', (function(_this) {
        return function() {
          return _this.space.height = _this.$spaceHeight.val();
        };
      })(this));
    };

    return SpaceDimensionInputs;

  })();

}).call(this);
