// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Circle = (function() {
    function Circle(position, radius, color) {
      this.draw = __bind(this.draw, this);
      this.centerX = position.x;
      this.centerY = position.y;
      this.radius = radius;
      this.color = color;
    }

    Circle.prototype.draw = function(context) {
      context.beginPath();
      context.arc(this.centerX, this.centerY, this.radius, 0, 2 * Math.PI, false);
      context.fillStyle = this.color;
      return context.fill();
    };

    return Circle;

  })();

}).call(this);
