// Generated by CoffeeScript 1.7.1
(function() {
  this.GInput = (function() {
    function GInput() {
      var $GInput;
      $GInput = $("#G");
      $GInput.val(Universe.G);
      $GInput.on('change', (function(_this) {
        return function() {
          return Universe.G = $GInput.val();
        };
      })(this));
    }

    return GInput;

  })();

}).call(this);
