// Generated by CoffeeScript 1.7.1
(function() {
  window.toInt = function(string) {
    return parseInt(string, 10);
  };

  window.randomColor = function() {
    return '#' + Math.floor(Math.random() * 16777215).toString(16);
  };

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

}).call(this);
