// Generated by CoffeeScript 1.7.1
(function() {
  require(['circle']);

  require(['entity']);

  require(['runner']);

  require(['universe']);

  require(['vector']);

  require(['jquery'], function($) {
    return $(document).ready(function() {
      var runner;
      return runner = new Runner(document.getElementById('canvas'));
    });
  });

}).call(this);
