// Generated by CoffeeScript 1.7.1
(function() {
  Number.prototype.randSign = function() {
    return (Math.random() < 0.5 ? 1 : -1) * this;
  };

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  String.prototype.toInt = function() {
    return parseInt(this, 10);
  };

}).call(this);
