// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Path = (function() {
    function Path(positions, color) {
      this.positions = positions;
      this.color = color;
      this.draw = __bind(this.draw, this);
    }

    Path.prototype.draw = function(context) {
      var i, position, _i, _len, _ref;
      context.beginPath();
      _ref = this.positions;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        position = _ref[i];
        context.lineTo(position.x, position.y);
      }
      context.strokeStyle = this.color;
      context.lineWidth = 2;
      return context.stroke();
    };

    return Path;

  })();

}).call(this);
