// Generated by CoffeeScript 1.7.1
(function() {
  this.PlayButton = (function() {
    function PlayButton(runner) {
      var $playBtn;
      $playBtn = $('#play');
      $playBtn.on('click', function() {
        if ($playBtn.html() === 'Play') {
          runner.play();
          return $playBtn.html('Pause');
        } else if ($playBtn.html() === 'Pause') {
          runner.pause();
          return $playBtn.html('Play');
        }
      });
    }

    return PlayButton;

  })();

}).call(this);
