// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Runner = (function() {
    function Runner(canvas) {
      this.tick = __bind(this.tick, this);
      var earth, fps, height, sun, width;
      width = canvas.width;
      height = canvas.height;
      this.context = canvas.getContext('2d');
      this.universe = new Universe(width, height);
      sun = new Entity({
        mass: 10,
        radius: 40,
        position: new Vector(width / 2, height / 2),
        color: 'yellow'
      });
      this.universe.addEntity(sun);
      earth = new Entity({
        mass: 1,
        radius: 10,
        position: new Vector(width / 2 + width / 8, height / 2),
        color: 'lightBlue'
      });
      this.universe.addEntity(earth);
      fps = 50;
      this.dt = 1000 / fps;
      setInterval(this.tick, this.dt);
    }

    Runner.prototype.tick = function() {
      return this.universe.tick(this.dt, this.context);
    };

    return Runner;

  })();

}).call(this);
