// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Runner = (function() {
    function Runner(canvas) {
      this.play = __bind(this.play, this);
      this.pause = __bind(this.pause, this);
      this.tick = __bind(this.tick, this);
      var earth, fps, height, sun, width;
      width = canvas.width;
      height = canvas.height;
      this.context = canvas.getContext('2d');
      this.universe = new Universe(width, height);
      sun = new Entity({
        name: 'sun',
        mass: 1000000,
        radius: 40,
        position: new Vector(width / 2, height / 2),
        color: '#ffe700'
      });
      this.universe.addEntity(sun);
      earth = new Entity({
        name: 'earth',
        mass: 1,
        radius: 10,
        position: new Vector(width / 2 + width / 8, height / 2),
        velocity: new Vector(0, -100),
        color: '#00fcff'
      });
      this.universe.addEntity(earth);
      fps = 50;
      this.dt = 1000 / fps;
      this.intervalId = setInterval(this.tick, this.dt);
      new PlayButton(this);
    }

    Runner.prototype.tick = function() {
      var dtInSeconds;
      dtInSeconds = this.dt / 1000;
      return this.universe.tick(dtInSeconds, this.context);
    };

    Runner.prototype.pause = function() {
      return clearInterval(this.intervalId);
    };

    Runner.prototype.play = function() {
      return this.intervalId = setInterval(this.tick, this.dt);
    };

    return Runner;

  })();

}).call(this);
