// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.RunsSimulation = (function() {
    function RunsSimulation(universe) {
      var fps, space;
      this.universe = universe;
      this.tick = __bind(this.tick, this);
      this.play = __bind(this.play, this);
      this.pause = __bind(this.pause, this);
      this.toggleRunning = __bind(this.toggleRunning, this);
      space = document.getElementById('space');
      this.context = space.getContext('2d');
      fps = 50;
      this.dt = 1000 / fps;
      this.play();
      this.playButton = new PlayButton(this);
    }

    RunsSimulation.prototype.toggleRunning = function() {
      if (this.running) {
        this.playButton.pause();
        return this.pause();
      } else {
        this.playButton.play();
        return this.play();
      }
    };

    RunsSimulation.prototype.pause = function() {
      clearInterval(this.intervalId);
      return this.running = false;
    };

    RunsSimulation.prototype.play = function() {
      this.intervalId = setInterval(this.tick, this.dt);
      return this.running = true;
    };

    RunsSimulation.prototype.tick = function() {
      var dtInSeconds;
      dtInSeconds = this.dt / 1000;
      return this.universe.tick(dtInSeconds, this.context);
    };

    return RunsSimulation;

  })();

}).call(this);
