// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.RunsSimulation = (function() {
    function RunsSimulation(universe) {
      var fps, space;
      this.universe = universe;
      this.tick = __bind(this.tick, this);
      this.play = __bind(this.play, this);
      this.pause = __bind(this.pause, this);
      this.toggleRunning = __bind(this.toggleRunning, this);
      space = document.getElementById('space');
      this.context = space.getContext('2d');
      fps = 30;
      this.dtInSeconds = 1 / fps;
      $("#fps").text(fps);
      $("#dt").text(this.dtInSeconds.toFixed(4));
      this.play();
    }

    RunsSimulation.prototype.toggleRunning = function() {
      if (this.running) {
        return this.pause();
      } else {
        return this.play();
      }
    };

    RunsSimulation.prototype.pause = function() {
      clearInterval(this.intervalId);
      return this.running = false;
    };

    RunsSimulation.prototype.play = function() {
      var dtInMilliseconds;
      dtInMilliseconds = this.dtInSeconds * 1000;
      this.intervalId = setInterval(this.tick, dtInMilliseconds);
      return this.running = true;
    };

    RunsSimulation.prototype.tick = function() {
      return this.universe.tick(this.dtInSeconds, this.context);
    };

    return RunsSimulation;

  })();

}).call(this);
