// Generated by CoffeeScript 1.7.1
(function() {
  describe("Vector", function() {
    return describe("#add", function() {
      return it("adds the vector with another", function() {
        var actual, other, vector;
        vector = new Vector(2, 2);
        other = new Vector(1, 3);
        actual = vector.add(other);
        expect(actual.x).toEqual(3);
        return expect(actual.y).toEqual(5);
      });
    });
  });

}).call(this);
