// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Vector = (function() {
    function Vector(x, y) {
      this.x = x;
      this.y = y;
      this.times = __bind(this.times, this);
      this.subtract = __bind(this.subtract, this);
      this.add = __bind(this.add, this);
    }

    Vector.prototype.add = function(vector) {
      return new Vector(this.x + vector.x, this.y + vector.y);
    };

    Vector.prototype.subtract = function(vector) {
      return this.add(vector.times(-1));
    };

    Vector.prototype.times = function(scalar) {
      return new Vector(scalar * this.x, scalar * this.y);
    };

    return Vector;

  })();

}).call(this);
