// Generated by CoffeeScript 1.7.1
(function() {
  this.AddEntityButton = (function() {
    function AddEntityButton(universe) {
      this.universe = universe;
      this.attachListeners();
    }

    AddEntityButton.prototype.attachListeners = function() {
      var $addEntityButton;
      $addEntityButton = $(".add-entity").find("button");
      return $addEntityButton.on('click', (function(_this) {
        return function() {
          var color, entity, entityCount, mass, posX, posY, position, radius, velX, velY, velocity;
          entityCount = _this.universe.entities.length;
          mass = toInt($("#mass-new-entity").val());
          radius = toInt($("#radius-new-entity").val());
          posX = toInt($("#position-x-new-entity").val());
          posY = toInt($("#position-y-new-entity").val());
          position = new Vector(posX, posY);
          velX = toInt($("#velocity-x-new-entity").val());
          velY = toInt($("#velocity-y-new-entity").val());
          velocity = new Vector(velX, velY);
          color = $("color-new-entity").val();
          entity = new Entity({
            name: "entity-" + (entityCount + 1),
            mass: mass,
            radius: radius,
            position: position,
            velocity: velocity,
            color: color
          });
          return _this.universe.addEntity(entity);
        };
      })(this));
    };

    return AddEntityButton;

  })();

}).call(this);
