// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.AddEntityButton = (function() {
    function AddEntityButton(universe) {
      this.universe = universe;
      this.attachListeners = __bind(this.attachListeners, this);
      this.attachListeners();
    }

    AddEntityButton.prototype.attachListeners = function() {
      var $space;
      $space = $("#space");
      return $space.on('click', (function(_this) {
        return function(e) {
          var color, entity, entityCount, name, position, x, y;
          x = e.pageX - $space.position().left;
          y = e.pageY - $space.position().top;
          position = new Vector(x, y);
          entityCount = _this.universe.entities.length;
          name = "entity-" + (entityCount + 1);
          color = randomColor();
          entity = new Entity({
            name: name,
            position: position,
            color: color
          });
          return _this.universe.addEntity(entity);
        };
      })(this));
    };

    return AddEntityButton;

  })();

}).call(this);
