// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.EntityInputs = (function() {
    function EntityInputs(entity) {
      this.entity = entity;
      this.attachListeners = __bind(this.attachListeners, this);
      this.attachListeners();
    }

    EntityInputs.prototype.attachListeners = function() {
      var $color, $mass, $posX, $posY, $radius, $velX, $velY, entityName;
      entityName = this.entity.name;
      $mass = $("#mass-" + entityName);
      $mass.val(this.entity.mass);
      $mass.on('change', (function(_this) {
        return function() {
          return _this.entity.mass = toInt($mass.val());
        };
      })(this));
      $radius = $("#radius-" + entityName);
      $radius.val(this.entity.radius);
      $radius.on('change', (function(_this) {
        return function() {
          return _this.entity.radius = toInt($radius.val());
        };
      })(this));
      $posX = $("#position-x-" + entityName);
      $posX.val(this.entity.position.x);
      $posX.on('change', (function(_this) {
        return function() {
          return _this.entity.position.x = toInt($posX.val());
        };
      })(this));
      $posY = $("#position-y-" + entityName);
      $posY.val(this.entity.position.y);
      $posY.on('change', (function(_this) {
        return function() {
          return _this.entity.position.y = toInt($posY.val());
        };
      })(this));
      $velX = $("#velocity-x-" + entityName);
      $velX.val(this.entity.velocity.x);
      $velX.on('change', (function(_this) {
        return function() {
          return _this.entity.velocity.x = toInt($velX.val());
        };
      })(this));
      $velY = $("#velocity-y-" + entityName);
      $velY.val(this.entity.velocity.y);
      $velY.on('change', (function(_this) {
        return function() {
          return _this.entity.velocity.y = toInt($velY.val());
        };
      })(this));
      $color = $("#color-" + entityName);
      $color.val(this.entity.color);
      return $color.on('change', (function(_this) {
        return function() {
          return _this.entity.color = $color.val();
        };
      })(this));
    };

    return EntityInputs;

  })();

}).call(this);
