// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PlayButton = (function() {
    function PlayButton(runner) {
      this.runner = runner;
      this.play = __bind(this.play, this);
      this.pause = __bind(this.pause, this);
      this.attachListeners = __bind(this.attachListeners, this);
      this.$playBtn = $('#play');
      this.attachListeners();
    }

    PlayButton.prototype.attachListeners = function() {
      return this.$playBtn.on('click', this.runner.toggleRunning);
    };

    PlayButton.prototype.pause = function() {
      return this.$playBtn.html('Play');
    };

    PlayButton.prototype.play = function() {
      return this.$playBtn.html('Pause');
    };

    return PlayButton;

  })();

}).call(this);
