// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PlayButton = (function() {
    function PlayButton(runner) {
      this.runner = runner;
      this.attachListeners = __bind(this.attachListeners, this);
      this.attachListeners();
    }

    PlayButton.prototype.attachListeners = function() {
      var $playBtn;
      $playBtn = $('#play');
      return $playBtn.on('click', (function(_this) {
        return function() {
          if ($playBtn.html() === 'Play') {
            _this.runner.play();
            return $playBtn.html('Pause');
          } else if ($playBtn.html() === 'Pause') {
            _this.runner.pause();
            return $playBtn.html('Play');
          }
        };
      })(this));
    };

    return PlayButton;

  })();

}).call(this);
