// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.SpaceClickListener = (function() {
    function SpaceClickListener(universe) {
      this.universe = universe;
      this.addEntity = __bind(this.addEntity, this);
      this.attachListeners = __bind(this.attachListeners, this);
      this.attachListeners();
    }

    SpaceClickListener.prototype.attachListeners = function() {
      return $("#space").on('click', this.addEntity);
    };

    SpaceClickListener.prototype.addEntity = function(e) {
      var $space, color, entity, entityCount, name, position, x, y;
      entityCount = this.universe.entities.length;
      name = "entity-" + (entityCount + 1);
      $space = $("#space");
      x = e.pageX - $space.position().left;
      y = e.pageY - $space.position().top;
      position = new Vector(x, y);
      color = randomColor();
      entity = new Entity({
        name: name,
        position: position,
        color: color
      });
      return this.universe.addEntity(entity);
    };

    return SpaceClickListener;

  })();

}).call(this);
