// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.UniverseConstantsInputs = (function() {
    function UniverseConstantsInputs() {
      this.attachListeners = __bind(this.attachListeners, this);
      this.setInitialValues = __bind(this.setInitialValues, this);
      this.$G = $("#G");
      this.setInitialValues();
      this.attachListeners();
    }

    UniverseConstantsInputs.prototype.setInitialValues = function() {
      return this.$G.val(Universe.G);
    };

    UniverseConstantsInputs.prototype.attachListeners = function() {
      return this.$G.on('change', (function(_this) {
        return function() {
          return Universe.G = _this.$G.val().toInt();
        };
      })(this));
    };

    return UniverseConstantsInputs;

  })();

}).call(this);
